global using System.Web;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Xunit;
global using Bunit;
global using AutoFixture.Xunit2;
global using NSubstitute;
global using Shouldly;
global using Carlton.Core.Utilities.Random;