global using static Carlton.Core.Flux.Internals.Errors.FluxErrors;
global using AutoFixture.Xunit2;
global using Bunit;
global using Bunit.TestDoubles;
global using NSubstitute;
global using RichardSzalay.MockHttp;
global using Shouldly;
global using Xunit;
global using Carlton.Core.Flux.Errors;
global using Carlton.Core.Flux.Tests.Common;
global using Carlton.Core.Flux.Tests.Common.Extensions;
global using Carlton.Core.Foundation.Tests;
